In [2]:
import numpy as np

In [3]:
np.array([3,4,3.14,5],dtype="float32") # or non-dtype

array([3.  , 4.  , 3.14, 5.  ], dtype=float32)

In [4]:
np.array([3,4,3.14,5],dtype="int") 

array([3, 4, 3, 5])

In [5]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [6]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.arange(0,40,2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [8]:
np.linspace(0,1,10) # numbers between 0-1 filled some range distrubtion 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.random.randint(0,10,(3,3)) # random between 0-10 , 3x3 matrix

array([[5, 3, 8],
       [5, 7, 8],
       [3, 1, 8]])

In [10]:
np.random.normal(10,4,(3,4)) # 1-aritmetic-mean | 2-standart-derivation | array-dimension

array([[ 7.59483698,  7.26883961,  9.79768252,  9.36977059],
       [14.19782091, 11.79666372,  0.88236146,  8.56946683],
       [ 9.33251155, 19.00721143, 14.33397084, 16.86492366]])

## Properties of Numpy-array ##
* ndim
* shape
* size
* dtype

In [11]:
a = np.random.randint(10,size=10)

In [12]:
a.ndim

1

In [13]:
a.shape

(10,)

In [14]:
a.size

10

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.random.randint(10,size=(3,5))

In [17]:
b.ndim

2

In [18]:
b.shape

(3, 5)

In [19]:
b.size

15

In [20]:
b.dtype

dtype('int64')

# Yeniden Şekillendirme (reshaping) #

In [21]:
a = np.arange(1,10)

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b = a.reshape((3,3))

In [24]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Birleştirme (Concatenation) #

In [25]:
x = np.array([1,2,3])
y = np.array([4,5,6])


In [26]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [27]:
z = np.array([7,8,9])

In [28]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2-dimensional ##

In [29]:
a = np.array([[1,2,3],[4,5,6]])

In [30]:
np.concatenate([a,a]) # with adding new row

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
np.concatenate([a,a],axis=1) #with adding new column

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array ayırma (Splitting) #

In [32]:
x = np.array([1,2,3,99,99,3,2,1])

In [33]:
a,b,c = np.split(x,[3,5]) # split from indexes 0-3 | 3-5 | 5-n

In [34]:
a

array([1, 2, 3])

In [35]:
b

array([99, 99])

In [36]:
c

array([3, 2, 1])

In [37]:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.vsplit(y,[2]) #vertical (by rows)  split from indexes 0-2 | 2-n rows

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [39]:
np.hsplit(y,[2]) # horizontal (by columns) split from indexes 0-2 | 2-n columns

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Array Sıralama (Sorting) ##

In [40]:
v = np.array([2,1,4,3,5])

In [41]:
np.sort(v)

array([1, 2, 3, 4, 5])

# 2-Boyutlu array sıralama #

In [42]:
m = np.random.normal(20,5,(3,3))

In [43]:
np.sort(m,axis=1) # row sorting

array([[13.49013761, 15.11773752, 15.31402697],
       [15.75424767, 19.79909919, 26.44579604],
       [13.64051509, 21.62301903, 23.1417004 ]])

In [44]:
np.sort(m,axis=0) # column sorting

array([[15.11773752, 13.49013761, 13.64051509],
       [23.1417004 , 15.75424767, 15.31402697],
       [26.44579604, 21.62301903, 19.79909919]])

# Index ile elemanlara erişmek #

In [45]:
a = np.random.randint(10,size=10)

In [46]:
a

array([7, 0, 0, 2, 3, 3, 8, 5, 1, 2])

In [47]:
a[0]

7

In [48]:
a[-1]

2

In [49]:
a[0] = 100
a

array([100,   0,   0,   2,   3,   3,   8,   5,   1,   2])

## İki Boyutlu ##

In [50]:
a = np.random.randint(10,size=(3,5))
a

array([[5, 4, 3, 3, 1],
       [6, 1, 6, 5, 0],
       [8, 5, 2, 2, 3]])

In [51]:
a[0,0] # row,column => with zero based index

5

In [52]:
a[2,4]

3

In [53]:
a[2,4] = 2.2 # data-type of matrix is already submitted (int-type).
# if we add any float number,  numpy converts to integer.

# Alt Küme Üzeride işlem yapmak #

In [54]:
a = np.random.randint(10,size=(5,5))
a

array([[7, 9, 4, 8, 4],
       [9, 8, 1, 1, 1],
       [6, 5, 9, 8, 8],
       [6, 7, 0, 0, 8],
       [3, 4, 3, 2, 6]])

In [55]:
alt_a = a[0:3,0:2]
alt_a

array([[7, 9],
       [9, 8],
       [6, 5]])

In [56]:
alt_a[0,0] = 99999
alt_a[1,1] = 99999

In [57]:
alt_a # alt_a changed

array([[99999,     9],
       [    9, 99999],
       [    6,     5]])

In [58]:
a # a changed too because of alt_a changes

array([[99999,     9,     4,     8,     4],
       [    9, 99999,     1,     1,     1],
       [    6,     5,     9,     8,     8],
       [    6,     7,     0,     0,     8],
       [    3,     4,     3,     2,     6]])

## copy kullanımı  ##

In [59]:
m = np.random.randint(10,size=(3,3))
m

array([[8, 5, 9],
       [8, 0, 5],
       [9, 7, 9]])

In [60]:
alt_b = m[0:1,0:2].copy()
alt_b

array([[8, 5]])

In [61]:
alt_b[0,0] = 99999
alt_b

array([[99999,     5]])

In [62]:
m

array([[8, 5, 9],
       [8, 0, 5],
       [9, 7, 9]])

# Fancy Index ile Elemanlara Erişmek # 

In [63]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [64]:
indexes = [1,3,5]

In [65]:
v[indexes]

array([ 3,  9, 15])

## 2 boyutta fancy ##

In [66]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [68]:
m[satir,sutun]

array([1, 5])

## fancy ile basit index ##

In [69]:
m[0,[1,2]] # 0. row (basit index) 1. ve 2. index (fancy)

array([1, 2])

## fancy ile slice ##

In [70]:
m[0: , [1,2]] # slice row ve fancy index

array([[1, 2],
       [4, 5],
       [7, 8]])

# Matematiksel İşlemler #

In [73]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [75]:
v-1

array([0, 1, 2, 3, 4])

In [77]:
v*5

array([ 5, 10, 15, 20, 25])

In [79]:
v/5

array([0, 0, 0, 0, 1])

In [81]:
v*5/10-1

array([-1,  0,  0,  1,  1])

In [ ]:
np.muli